**Different ways of creating a series**

# Series
* A pandas Series is a **one-dimensional array**-like object in Python that can hold data of any type (integers, floats, strings, etc.).
* It is part of the pandas library, which is widely used for data manipulation and analysis.

#Key Features of a pandas Series

**One-dimensional:**

* A Series is like a **column** in a table or a single list of values.

**Indexing:**

* Each element in a Series has an associated label called an **index**.
* By default, this index is just the row number (starting from 0), but you can also assign custom labels to it.

**Homogeneous Data Type:**

* All elements in a Series have the same data type, unlike a DataFrame, which can have different types of data in different columns.

**Summary**

* A pandas Series is a powerful tool for handling one-dimensional data with ease.
* It provides flexibility with indexing and supports a wide range of operations, making it an essential component of the pandas library for data analysis in Python.

**Empty Series**

In [ ]:
#(i) Empty Series
import pandas as pd
series = pd.Series()
series

Series([], dtype: object)

**Series using Array**

In [ ]:
#(ii) Series using Array
import numpy as np
array = np.array([1,2,3])
series = pd.Series(array)
series

0    1
1    2
2    3
dtype: int64

**Series using List**

In [ ]:
#(iii) Series using List
#series = pd.Series([10,20,30])
series = pd.Series([10,'PC',20)])
series


#series

0    CS
1    PC
2    IT
dtype: object

**Series using Dictionary**

In [ ]:
#(iv) Series using Dictionary
series = pd.Series({'Salem' : 30, 'Bangalore' : 25, 'Melbourne' : 22})
series

Salem        30
Bangalore    25
Melbourne    22
dtype: int64

**Series using Tuple**

In [ ]:
#(V) Series using tuple
series = pd.Series([('Salem' , 30), ('Bangalore' , 25), ('Melbourne' , 22)])
series

0        (Salem, 30)
1    (Bangalore, 25)
2    (Melbourne, 22)
dtype: object

**Changing index names**

In [ ]:
#Changing index names
import numpy as np
array = np.array([90,95,96])
series = pd.Series(array,index=['DS','FDS', 'OOPS'])
series

DS      90
FDS     95
OOPS    96
dtype: int64

# DataFrame
* A pandas DataFrame is a two-dimensional, tabular data structure in Python that is part of the pandas library, widely used for data manipulation and analysis.
* Think of it as an Excel spreadsheet or a SQL table in Python.

**Key Features of a pandas DataFrame**

**Two-dimensional:**

* Data is organized in rows and columns, similar to a table.
Heterogeneous Data:

* Different columns can hold different types of data (e.g., integers, floats, strings).

**Labeled Axes:**

* Both rows and columns have labels (indices), which makes it easy to access and manipulate data.

**Summary**

**Series:**
* All elements have the same data type.

**DataFrame:**
* Different columns can have different data types.

     * By keeping data types homogeneous in a Series, pandas ensures efficient storage and computation.

     * This is in contrast to a DataFrame, where the flexibility to store different data types in different columns is useful for handling more complex datasets.

**Different ways of creating a DataFrame**

In [ ]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
#s
df = pd.DataFrame(array)
df

   0  1  2
0  1  2  3
1  4  5  6

**load excel files**

In [2]:
#load excel files
import pandas as pd
df = pd.read_excel("/content/sample_data/II_C.xlsx")
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/II_C.xlsx'

**load csv files**

In [ ]:
#load csv files
df = pd.read_csv("/content/sample_data/II_C.csv", encoding='cp1252')
#print(df)
df

        Reg No.   Student’s Name  DS   FDS  OOPS
0   6.11221E+11        SANTOSH M  85   NaN    78
1   6.11221E+11        SARANYA A  85  90.0    95
2   6.11221E+11      SARAVANAN S  85  90.0    95
3   6.11221E+11  SARGURURATHNA M  85  90.0    95
4   6.11221E+11      SATHAPPAN V  85  90.0    95
..          ...              ...  ..   ...   ...
62          LE1          VIJAY.T  85  90.0    95
63          LE2          VIPIN.R  85  90.0    95
64          LE3   VISHNU BALAN.O  85  90.0    95
65          LE4        VIYASAN.S  85  90.0    95
66          LE5  ABILASH KUMAR R  90  92.0    94

[67 rows x 5 columns]

In [ ]:
txt = pd.read_csv('/content/sample_data/Sample.txt')
#txt = pd.read_table('/content/sample_data/Sample.txt')
txt

Empty DataFrame
Columns: [Hi 2024]
Index: []

**create df using dictionary**

In [ ]:
# create df using dictionary
dictionary = {'City': ['Salem', 'Bangalore','Melbourne'],  'Temperature' : [32, 27, 21]}
#df = pd.Series(dictionary)
df = pd.DataFrame(dictionary)
df

        City  Temperature
0      Salem           32
1  Bangalore           27
2  Melbourne           21

**create df using list**

In [ ]:
# create df using list
list = pd.DataFrame([90,95,97],index = ['DS', 'FDS', 'OOPS'])
list

       0
DS    90
FDS   95
OOPS  97

**create df using list of tuples**

In [ ]:
tuple = pd.DataFrame([('Salem' , 30), ('Bangalore' , 25), ('Melbourne' , 22)])
tuple

           0   1
0      Salem  30
1  Bangalore  25
2  Melbourne  22

**Series attributes**

(i)index

(ii)array

(iii)values

(iv)name

(v)shape

(vi)ndim

(vii)size

(viii)nbytes

(ix)memory_usage

(x)empty

# (i)**index**

In [ ]:
#Series attributes
series = pd.Series([90,95,98],index=['DS','FDS', 'OOPS'])
series.index
#series.index

Index(['DS', 'FDS', 'OOPS'], dtype='object')

# (ii) Array

In [ ]:
series.array

<PandasArray>
[90, 95, 98]
Length: 3, dtype: int64

## (iii)Values

In [ ]:
series.values

array([90, 95, 98])

# (iv) Name

In [ ]:
s3 = pd.Series([1, 2, 3], name ="SNO")
s3.name

'SNO'

# (V)Shape

In [ ]:
series.shape

(3,)

# (Vi)Ndim

In [ ]:
series.ndim

1

# (Vii)Size

In [ ]:
series.size

3

# (Viii)Nbytes

In [ ]:
s4=pd.Series([10,20,30,40],dtype='int32')
s4.nbytes

8

# (IX)Dtype

In [ ]:
s3.dtype

dtype('int64')

# (X)Memory_usage

In [ ]:
s4 = pd.Series([10,20,30,40])
#s4.nbytes
s4.memory_usage()
#s4.nbytes
#s4.memory_usage(index = False)

32

# (Xi)Empty

In [ ]:
s5 = pd.Series()
s5.empty

False

# (Xii)hasnans and count()

In [ ]:
import numpy as np
import pandas as pd
a=pd.Series(data=[1,2,3,np.NaN])
print(a.empty)
print(a.hasnans)
print(len(a))
print(a.count( ))
#print(type(np.NaN))

False
True
4
3
<class 'float'>

In [ ]:
b=pd.Series(data=[4.9,8.2,5.6],index=['x','y','z'])
print(b.empty)
print(b.hasnans)
print(len(b))
print(b.count( ))

False
False
3
3

In [ ]:
c=pd.Series()
print(c.empty)
print(c.hasnans)
print(len(c))
print(c.count( ))

True
False
0
0

# performing mathematical operations in pandas series

In [ ]:
#performing mathematical operations in pandas series
#Note : internally operator calls suitable function
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])
#s1.add(s2)
#s1 + s2
#s1.sub(s2)
#s1 - s2
#s1.multiply(s2)
#s1 * s2
#s1.divide(s2)
#s1 / s2
#s1.mod(s2)
#s1 * s2
#s1.pow(s2)
#s1 ** s2
#s1.le(s2)
#s1 < s2
#s1.gt(s2)
#s1 > s2
#s1.equals(s2)
#s1 == s2

False

**Methods for indexing in DataFrame**

# head() :
* Return top n rows of a data frame

# tail() :
* Return bottom n rows of a data frame

# DataFrame.[ ] :
* This function also known as indexing operator

e.g

  **DataFame.[ 'Columnname']** ---> Single column

  **DataFrame.[ ['Columnname1, Columnname2']]** ---> Multiple columns

  **DataFrame.[ ['Columnname1, Columnname2'][start,stop,step]]**    
              --->Slicing for these two columns

  **If we want to get data in individual rows then**

            for index,row in df.iterrows():
                print(index,row)

  **Dataframe.loc[ ]** ---> This function is used for displaying data in rows based on labels

  **Dataframe.iloc[ ]** ---> This function is used for displaying data in rows based on positions or integer

  **Dataframe.ix[]** ---> This function is used for displaying data in rows based on both label and integer









loc![pandas-difference-loc-vs-iloc.png]()

In [ ]:
#accessing/slicing
df

        Reg No.   Student’s Name  DS   FDS OOPS
0   6.11221E+11        SANTOSH M  85   NaN
1   6.11221E+11        SARANYA A  85  90.0   95
2   6.11221E+11      SARAVANAN S  85  90.0   95
3   6.11221E+11  SARGURURATHNA M  85  90.0   95
4   6.11221E+11      SATHAPPAN V  85  90.0   95
..          ...              ...  ..   ...  ...
62          LE1          VIJAY.T  85  90.0   95
63          LE2          VIPIN.R  85  90.0   95
64          LE3   VISHNU BALAN.O  85  90.0   95
65          LE4        VIYASAN.S  85  90.0   95
66          LE5  ABILASH KUMAR R  90  92.0   94

[67 rows x 5 columns]

In [ ]:
df.tail()

   Reg No.   Student’s Name  DS   FDS OOPS
62     LE1          VIJAY.T  85  90.0   95
63     LE2          VIPIN.R  85  90.0   95
64     LE3   VISHNU BALAN.O  85  90.0   95
65     LE4        VIYASAN.S  85  90.0   95
66     LE5  ABILASH KUMAR R  90  92.0   94

In [ ]:
df.head()

       Reg No.   Student’s Name  DS   FDS OOPS
0  6.11221E+11        SANTOSH M  85   NaN
1  6.11221E+11        SARANYA A  85  90.0   95
2  6.11221E+11      SARAVANAN S  85  90.0   95
3  6.11221E+11  SARGURURATHNA M  85  90.0   95
4  6.11221E+11      SATHAPPAN V  85  90.0   95

In [ ]:
df.head(10)

       Reg No.      Student’s Name  DS   FDS OOPS
0  6.11221E+11           SANTOSH M  85   NaN
1  6.11221E+11           SARANYA A  85  90.0   95
2  6.11221E+11         SARAVANAN S  85  90.0   95
3  6.11221E+11     SARGURURATHNA M  85  90.0   95
4  6.11221E+11         SATHAPPAN V  85  90.0   95
5  6.11221E+11           SATHISH D  85  90.0   95
6  6.11221E+11       SATHISKUMAR P  85  90.0   95
7  6.11221E+11         SATHYARAM R  87  90.0   92
8  6.11221E+11  SELVAGANAPATHI V M  87  90.0   92
9  6.11221E+11      SETHURAMAN C R  87  90.0   92

In [ ]:
df.tail(7)

        Reg No.   Student’s Name  DS   FDS OOPS
60  6.11221E+11       YUVASREE M  85  90.0   95
61  6.11221E+11        YUVASRI V  85  90.0   95
62          LE1          VIJAY.T  85  90.0   95
63          LE2          VIPIN.R  85  90.0   95
64          LE3   VISHNU BALAN.O  85  90.0   95
65          LE4        VIYASAN.S  85  90.0   95
66          LE5  ABILASH KUMAR R  90  92.0   94

In [ ]:
df.describe()

              DS        FDS       OOPS
count  67.000000  66.000000  67.000000
mean   85.432836  90.712121  94.194030
std     0.957014   1.982734   2.317514
min    85.000000  90.000000  78.000000
25%    85.000000  90.000000  95.000000
50%    85.000000  90.000000  95.000000
75%    85.000000  90.000000  95.000000
max    90.000000  99.000000  95.000000

In [ ]:
df.shape

(67, 5)

In [ ]:
#single column
df['FDS']

0      NaN
1     90.0
2     90.0
3     90.0
4     90.0
      ...
62    90.0
63    90.0
64    90.0
65    90.0
66    92.0
Name: FDS, Length: 67, dtype: float64

In [ ]:
#single column with top 10 row values
df['FDS'].head(10)

0     NaN
1    90.0
2    90.0
3    90.0
4    90.0
5    90.0
6    90.0
7    90.0
8    90.0
9    90.0
Name: FDS, dtype: float64

In [ ]:
#multiple columns
df[['FDS','OOPS']]

     FDS  OOPS
0    NaN    78
1   90.0    95
2   90.0    95
3   90.0    95
4   90.0    95
..   ...   ...
62  90.0    95
63  90.0    95
64  90.0    95
65  90.0    95
66  92.0    94

[67 rows x 2 columns]

In [ ]:
#multiple columns with top 7 row values
df[['FDS','OOPS']].head(7)

    FDS  OOPS
0   NaN    78
1  90.0    95
2  90.0    95
3  90.0    95
4  90.0    95
5  90.0    95
6  90.0    95

In [ ]:
#multiple columns without slicing
df[['Student’s Name','FDS', 'OOPS']]

     Student’s Name   FDS  OOPS
0         SANTOSH M   NaN    78
1         SARANYA A  90.0    95
2       SARAVANAN S  90.0    95
3   SARGURURATHNA M  90.0    95
4       SATHAPPAN V  90.0    95
..              ...   ...   ...
62          VIJAY.T  90.0    95
63          VIPIN.R  90.0    95
64   VISHNU BALAN.O  90.0    95
65        VIYASAN.S  90.0    95
66  ABILASH KUMAR R  92.0    94

[67 rows x 3 columns]

In [ ]:
#multiple columns with slicing
df[['Student’s Name','DS','FDS', 'OOPS',]][15:20:1]

    Student’s Name  DS   FDS  OOPS
15     SOURISH A P  87  95.0    92
16   SOWANTHARYA S  87  96.0    92
17  SOWENDARYA P K  87  97.0    92
18     SOWNDARYA K  87  98.0    92
19     SREEJITHA S  85  99.0    95

In [ ]:
#to display range of rows then use slicing
df[20:35]

20    85
21    85
22    85
23    85
24    85
25    85
26    85
27    85
28    85
29    85
30    85
31    85
32    85
33    85
34    85
35    85
Name: DS, dtype: int64

In [ ]:
#to display range of rows then use slicing
df[0:8:2]

       Reg No. Student’s Name  DS   FDS  OOPS
0  6.11221E+11      SANTOSH M  85   NaN    78
2  6.11221E+11    SARAVANAN S  85  90.0    95
4  6.11221E+11    SATHAPPAN V  85  90.0    95
6  6.11221E+11  SATHISKUMAR P  85  90.0    95

In [ ]:
#to display a single row then use loc
df.loc[2]

Reg No.           6.11221E+11
Student’s Name    SARAVANAN S
DS                         85
FDS                        90
OOPS                       95
Name: 2, dtype: object

In [ ]:
#to display range of rows then use slicing or loc
#Note : last index is inclusive
df.loc[0:8]

       Reg No.      Student’s Name  DS  FDS  OOPS
0  6.11221E+11           SANTOSH M  85   90    95
1  6.11221E+11           SARANYA A  85   90    95
2  6.11221E+11         SARAVANAN S  85   90    95
3  6.11221E+11     SARGURURATHNA M  85   90    95
4  6.11221E+11         SATHAPPAN V  85   90    95
5  6.11221E+11           SATHISH D  85   90    95
6  6.11221E+11       SATHISKUMAR P  85   90    95
7  6.11221E+11         SATHYARAM R  87   90    92
8  6.11221E+11  SELVAGANAPATHI V M  87   90    92

In [ ]:
#iterating index and rows
for index,rows in df.iterrows():
    print(index,rows)

0 Reg No.           6.11221E+11
Student’s Name      SANTOSH M
DS                         85
FDS                       NaN
OOPS                       78
Name: 0, dtype: object
1 Reg No.           6.11221E+11
Student’s Name      SARANYA A
DS                         85
FDS                      90.0
OOPS                       95
Name: 1, dtype: object
2 Reg No.           6.11221E+11
Student’s Name    SARAVANAN S
DS                         85
FDS                      90.0
OOPS                       95
Name: 2, dtype: object
3 Reg No.               6.11221E+11
Student’s Name    SARGURURATHNA M
DS                             85
FDS                          90.0
OOPS                           95
Name: 3, dtype: object
4 Reg No.           6.11221E+11
Student’s Name    SATHAPPAN V
DS                         85
FDS                      90.0
OOPS                       95
Name: 4, dtype: object
5 Reg No.           6.11221E+11
Student’s Name      SATHISH D
DS                         85
FDS                      90.0
OOPS                       95
Name: 5, dtype: object
6 Reg No.             6.11221E+11
Student’s Name    SATHISKUMAR P
DS                           85
FDS                        90.0
OOPS                         95
Name: 6, dtype: object
7 Reg No.           6.11221E+11
Student’s Name    SATHYARAM R
DS                         87
FDS                      90.0
OOPS                       92
Name: 7, dtype: object
8 Reg No.                  6.11221E+11
Student’s Name    SELVAGANAPATHI V M
DS                                87
FDS                             90.0
OOPS                              92
Name: 8, dtype: object
9 Reg No.              6.11221E+11
Student’s Name    SETHURAMAN C R
DS                            87
FDS                         90.0
OOPS                          92
Name: 9, dtype: object
10 Reg No.           6.11221E+11
Student’s Name    SHABARI K S
DS                         87
FDS                      90.0
OOPS                       92
Name: 10, dtype: object
11 Reg No.           6.11221E+11
Student’s Name     SHARMILA S
DS                         87
FDS                      91.0
OOPS                       92
Name: 11, dtype: object
12 Reg No.           6.11221E+11
Student’s Name     SHIBIE R M
DS                         87
FDS                      92.0
OOPS                       92
Name: 12, dtype: object
13 Reg No.              6.11221E+11
Student’s Name    SHREENIVASAN S
DS                            87
FDS                         93.0
OOPS                          92
Name: 13, dtype: object
14 Reg No.           6.11221E+11
Student’s Name    SHRIYAA S V
DS                         87
FDS                      94.0
OOPS                       92
Name: 14, dtype: object
15 Reg No.           6.11221E+11
Student’s Name    SOURISH A P
DS                         87
FDS                      95.0
OOPS                       92
Name: 15, dtype: object
16 Reg No.             6.11221E+11
Student’s Name    SOWANTHARYA S
DS                           87
FDS                        96.0
OOPS                         92
Name: 16, dtype: object
17 Reg No.              6.11221E+11
Student’s Name    SOWENDARYA P K
DS                            87
FDS                         97.0
OOPS                          92
Name: 17, dtype: object
18 Reg No.           6.11221E+11
Student’s Name    SOWNDARYA K
DS                         87
FDS                      98.0
OOPS                       92
Name: 18, dtype: object
19 Reg No.           6.11221E+11
Student’s Name    SREEJITHA S
DS                         85
FDS                      99.0
OOPS                       95
Name: 19, dtype: object
20 Reg No.                  6.11221E+11
Student’s Name    SREE SUDHARSAN A M
DS                                85
FDS                             90.0
OOPS                              95
Name: 20, dtype: object
21 Reg No.                   6.11221E+11
Student’s Name    SRIPOORNIMADEVI T S
DS                                 85
FDS                              90.0
OOPS                               95
Name: 21, dtype: object
22 Reg No.            6.11221E+11
Student’s Name    SRIRANJANI M
DS                          85
FDS                       90.0
OOPS                        95
Name: 22, dtype: object
23 Reg No.           6.11221E+11
Student’s Name       SUBASH S
DS                         85
FDS                      90.0
OOPS                       95
Name: 23, dtype: object
24 Reg No.           6.11221E+11
Student’s Name      SUBASRI C
DS                         85
FDS                      90.0
OOPS                       95
Name: 24, dtype: object
25 Reg No.           6.11221E+11
Student’s Name     SUBESHAN M
DS                         85
FDS                      90.0
OOPS                       95
Name: 25, dtype: object
26 Reg No.            6.11221E+11
Student’s Name    SUBIKCHA K B
DS                          85
FDS                       90.0
OOPS                        95
Name: 26, dtype: object
27 Reg No.              6.11221E+11
Student’s Name    SUDHARSHAN M S
DS                            85
FDS                         90.0
OOPS                          95
Name: 27, dtype: object
28 Reg No.               6.11221E+11
Student’s Name    SUGANESHWARAN S
DS                             85
FDS                          90.0
OOPS                           95
Name: 28, dtype: object
29 Reg No.                 6.11221E+11
Student’s Name    SUGAVANESHWARAN K
DS                               85
FDS                            90.0
OOPS                             95
Name: 29, dtype: object
30 Reg No.           6.11221E+11
Student’s Name     SUHASINI P
DS                         85
FDS                      90.0
OOPS                       95
Name: 30, dtype: object
31 Reg No.           6.11221E+11
Student’s Name    SUNDARESH S
DS                         85
FDS                      90.0
OOPS                       95
Name: 31, dtype: object
32 Reg No.             6.11221E+11
Student’s Name    SUSHMITHA B A
DS                           85
FDS                        90.0
OOPS                         95
Name: 32, dtype: object
33 Reg No.           6.11221E+11
Student’s Name       SWATHI V
DS                         85
FDS                      90.0
OOPS                       95
Name: 33, dtype: object
34 Reg No.           6.11221E+11
Student’s Name     SWETHA S M
DS                         85
FDS                      90.0
OOPS                       95
Name: 34, dtype: object
35 Reg No.           6.11221E+11
Student’s Name       SWETHA M
DS                         85
FDS                      90.0
OOPS                       95
Name: 35, dtype: object
36 Reg No.            6.11221E+11
Student’s Name    SYED ANEES J
DS                          85
FDS                       90.0
OOPS                        95
Name: 36, dtype: object
37 Reg No.           6.11221E+11
Student’s Name      THARANI R
DS                         85
FDS                      90.0
OOPS                       95
Name: 37, dtype: object
38 Reg No.           6.11221E+11
Student’s Name      THARANI K
DS                         85
FDS                      90.0
OOPS                       95
Name: 38, dtype: object
39 Reg No.               6.11221E+11
Student’s Name    THOUSHIKAMARY F
DS                             85
FDS                          90.0
OOPS                           95
Name: 39, dtype: object
40 Reg No.           6.11221E+11
Student’s Name       THREKA M
DS                         85
FDS                      90.0
OOPS                       95
Name: 40, dtype: object
41 Reg No.           6.11221E+11
Student’s Name     TRISHA J V
DS                         85
FDS                      90.0
OOPS                       95
Name: 41, dtype: object
42 Reg No.             6.11221E+11
Student’s Name    UDHAYAKIRAN G
DS                           85
FDS                        90.0
OOPS                         95
Name: 42, dtype: object
43 Reg No.           6.11221E+11
Student’s Name     VAISHIYA R
DS                         85
FDS                      90.0
OOPS                       95
Name: 43, dtype: object
44 Reg No.            6.11221E+11
Student’s Name    VALLIAPPAN V
DS                          85
FDS                       90.0
OOPS                        95
Name: 44, dtype: object
45 Reg No.           6.11221E+11
Student’s Name     VARSHINI G
DS                         85
FDS                      90.0
OOPS                       95
Name: 45, dtype: object
46 Reg No.            6.11221E+11
Student’s Name    VENKATESAN M
DS                          85
FDS                       90.0
OOPS                        95
Name: 46, dtype: object
47 Reg No.           6.11221E+11
Student’s Name    VENKATESH K
DS                         85
FDS                      90.0
OOPS                       95
Name: 47, dtype: object
48 Reg No.           6.11221E+11
Student’s Name    VENKATRAM S
DS                         85
FDS                      90.0
OOPS                       95
Name: 48, dtype: object
49 Reg No.           6.11221E+11
Student’s Name        VIBAV M
DS                         85
FDS                      90.0
OOPS                       95
Name: 49, dtype: object
50 Reg No.           6.11221E+11
Student’s Name      VIGNESH S
DS                         85
FDS                      90.0
OOPS                       95
Name: 50, dtype: object
51 Reg No.              6.11221E+11
Student’s Name    VIGNESHWARAN K
DS                            85
FDS                         90.0
OOPS                          95
Name: 51, dtype: object
52 Reg No.           6.11221E+11
Student’s Name      VIJAY K R
DS                         85
FDS                      90.0
OOPS                       95
Name: 52, dtype: object
53 Reg No.             6.11221E+11
Student’s Name    VIJAYAKUMAR G
DS                           85
FDS                        90.0
OOPS                         95
Name: 53, dtype: object
54 Reg No.           6.11221E+11
Student’s Name        VIKAS P
DS                         85
FDS                      90.0
OOPS                       95
Name: 54, dtype: object
55 Reg No.           6.11221E+11
Student’s Name    VINEETH K R
DS                         85
FDS                      90.0
OOPS                       95
Name: 55, dtype: object
56 Reg No.           6.11221E+11
Student’s Name     VISHNAVI R
DS                         85
FDS                      90.0
OOPS                       95
Name: 56, dtype: object
57 Reg No.           6.11221E+11
Student’s Name        VIVEK S
DS                         85
FDS                      90.0
OOPS                       95
Name: 57, dtype: object
58 Reg No.           6.11221E+11
Student’s Name       YAMINI M
DS                         85
FDS                      90.0
OOPS                       95
Name: 58, dtype: object
59 Reg No.           6.11221E+11
Student’s Name      YUVARAJ R
DS                         85
FDS                      90.0
OOPS                       95
Name: 59, dtype: object
60 Reg No.           6.11221E+11
Student’s Name     YUVASREE M
DS                         85
FDS                      90.0
OOPS                       95
Name: 60, dtype: object
61 Reg No.           6.11221E+11
Student’s Name      YUVASRI V
DS                         85
FDS                      90.0
OOPS                       95
Name: 61, dtype: object
62 Reg No.               LE1
Student’s Name    VIJAY.T
DS                     85
FDS                  90.0
OOPS                   95
Name: 62, dtype: object
63 Reg No.               LE2
Student’s Name    VIPIN.R
DS                     85
FDS                  90.0
OOPS                   95
Name: 63, dtype: object
64 Reg No.                      LE3
Student’s Name    VISHNU BALAN.O
DS                            85
FDS                         90.0
OOPS                          95
Name: 64, dtype: object
65 Reg No.                 LE4
Student’s Name    VIYASAN.S
DS                       85
FDS                    90.0
OOPS                     95
Name: 65, dtype: object
66 Reg No.                       LE5
Student’s Name    ABILASH KUMAR R
DS                             90
FDS                          92.0
OOPS                           94
Name: 66, dtype: object

In [ ]:
#iterating index and rows with studnet name alone
for index,rows in df.iterrows():
    print(index,rows['Student’s Name'])
    #print(index,rows[['Reg No.','Student’s Name'])

0 SANTOSH M
1 SARANYA A
2 SARAVANAN S
3 SARGURURATHNA M
4 SATHAPPAN V
5 SATHISH D
6 SATHISKUMAR P
7 SATHYARAM R
8 SELVAGANAPATHI V M
9 SETHURAMAN C R
10 SHABARI K S
11 SHARMILA S
12 SHIBIE R M
13 SHREENIVASAN S
14 SHRIYAA S V
15 SOURISH A P
16 SOWANTHARYA S
17 SOWENDARYA P K
18 SOWNDARYA K
19 SREEJITHA S
20 SREE SUDHARSAN A M
21 SRIPOORNIMADEVI T S
22 SRIRANJANI M
23 SUBASH S
24 SUBASRI C
25 SUBESHAN M
26 SUBIKCHA K B
27 SUDHARSHAN M S
28 SUGANESHWARAN S
29 SUGAVANESHWARAN K
30 SUHASINI P
31 SUNDARESH S
32 SUSHMITHA B A
33 SWATHI V
34 SWETHA S M
35 SWETHA M
36 SYED ANEES J
37 THARANI R
38 THARANI K
39 THOUSHIKAMARY F
40 THREKA M
41 TRISHA J V
42 UDHAYAKIRAN G
43 VAISHIYA R
44 VALLIAPPAN V
45 VARSHINI G
46 VENKATESAN M
47 VENKATESH K
48 VENKATRAM S
49 VIBAV M
50 VIGNESH S
51 VIGNESHWARAN K
52 VIJAY K R
53 VIJAYAKUMAR G
54 VIKAS P
55 VINEETH K R
56 VISHNAVI R
57 VIVEK S
58 YAMINI M
59 YUVARAJ R
60 YUVASREE M
61 YUVASRI V
62 VIJAY.T
63 VIPIN.R
64 VISHNU BALAN.O
65 VIYASAN.S

In [ ]:
#displaying row based on some condition
df.loc[df['Reg No.'] == 611221104174]
#df.loc[df['Student’s Name']=='SANTOSH M']

Empty DataFrame
Columns: [Reg No., Student’s Name, DS, FDS, OOPS]
Index: []

# Sorting
* Sorting is one of the operations performed on the dataframe based on conditional requirements.
* We can sort dataframe alphabetically as well as in numerical order also.

**Method 1: Using sort_values() method**

**Syntax:**
df_name.sort_values(by column_name, axis=0, ascending=True, inplace=False, kind=’quicksort’, na_position=’last’, ignore_index=False, key=None)

# Parameters:
#by:
* name of list or column it should sort by

# axis:
* Axis to be sorted.('0' or 'index' or 1 or ‘column’) by default its 0.(column number)

# ascending:
* Sorting ascending or descending. Specify lists of bool values for multiple sort orders.
* The list of bool values must match the no. of values of ‘by’ i.e. column_names.
* By default it is true.

#inplace:
* By default it is false. but if its value is true it performs operation in-place i.e. in proper place.

#kind:

* Choice of sorting algorithm like quick sort. merge sort, heap sort. by default it is quick sort.

In [ ]:
import pandas as pd
technologies = ({
    'Courses':["Spark","Hadoop","pandas","Oracle","Java"],
    'Fee' :[20000,25000,26000,22000,20000],
    'Duration':['30days','35days','40days','50days','60days'],
    'Discount':[1000,2300,1500,1200,2500]
               })
df2 = pd.DataFrame(technologies, index = ['r1','r2','r3','r4','r0'])
df2

   Courses    Fee Duration  Discount
r1   Spark  20000   30days      1000
r2  Hadoop  25000   35days      2300
r3  pandas  26000   40days      1500
r4  Oracle  22000   50days      1200
r0    Java  20000   60days      2500

#Sort Multiple Columns in pandas DataFrame

* By using the sort_values() method you can sort multiple columns in DataFrame by ascending or descending order.
* When not specified order, all columns specified are sorted by ascending order.

In [ ]:
# Sort multiple columns
df2.sort_values(['Fee', 'Discount'])
df2

   Courses    Fee Duration  Discount
r1   Spark  20000   30days      1000
r2  Hadoop  25000   35days      2300
r3  pandas  26000   40days      1500
r4  Oracle  22000   50days      1200
r0    Java  20000   60days      2500

In [ ]:
#In case if you wanted to update the existing DataFrame use inplace=True.
# Sort ascending order
df2.sort_values(by=['Fee','Discount'], inplace=True)
df2

   Courses    Fee Duration  Discount
r1   Spark  20000   30days      1000
r0    Java  20000   60days      2500
r4  Oracle  22000   50days      1200
r2  Hadoop  25000   35days      2300
r3  pandas  26000   40days      1500

#Sort in an Ascending Order
* Use ascending param to sort the DataFrame in ascending or descending order.
* When you have multiple sorting columns. By default, it sorts in ascending #order.

In [ ]:
df2

   Courses    Fee Duration  Discount
r1   Spark  20000   30days      1000
r0    Java  20000   60days      2500
r4  Oracle  22000   50days      1200
r2  Hadoop  25000   35days      2300
r3  pandas  26000   40days      1500

In [ ]:
# Sort ascending order
df2.sort_values(by=['Fee','Discount'], inplace=True,
               ascending = [True, True])
df2

   Courses    Fee Duration  Discount
r1   Spark  20000   30days      1000
r4  Oracle  22000   50days      1200
r3  pandas  26000   40days      1500
r2  Hadoop  25000   35days      2300
r0    Java  20000   60days      2500

#Sort Multiple Columns in Descending Order
* In case you wanted to sort by descending order, use ascending=False. You can also specify different sorting orders for each input.

In [ ]:
# Sort descending order
df2.sort_values(by=['Fee','Discount'], inplace=True,
               ascending = [True, False])
df2

   Courses    Fee Duration  Discount
r0    Java  20000   60days      2500
r1   Spark  20000   30days      1000
r4  Oracle  22000   50days      1200
r2  Hadoop  25000   35days      2300
r3  pandas  26000   40days      1500

#Using sort_index() method


  # Syntax:
  df_name.sort_index(axis=0, level=None, ascending=True, inplace=False, kind=’quicksort’, na_position=’last’, sort_remaining=True, ignore_index=False, key=None)

In [ ]:
print('SORTED DATAFRAME')
df2.sort_index(ascending=False)

SORTED DATAFRAME

   Courses    Fee Duration  Discount
r4  Oracle  22000   50days      1200
r3  pandas  26000   40days      1500
r2  Hadoop  25000   35days      2300
r1   Spark  20000   30days      1000
r0    Java  20000   60days      2500

In [ ]:
c = pd.read_excel('/Sample.xlsx')
ef = pd.DataFrame(c)
ef.sort_values('Regno')

   Regno  FDS  OOPS  DS
0      1   80    90  75
2      2   85    88  92
4      3   90    95  65
1      4   76    88  99
3      5   88    76  65

In [ ]:
ef.sort_values(['Regno','FDS'],ascending = [1,0])

   Regno  FDS  OOPS  DS
0      1   80    90  75
2      2   85    88  92
4      3   90    95  65
1      4   76    88  99
3      5   88    76  65

In [ ]:
df.sort_values('FDS',ascending = False)

        Reg No.  Student’s Name  DS   FDS  OOPS
19  6.11221E+11     SREEJITHA S  85  99.0    95
18  6.11221E+11     SOWNDARYA K  87  98.0    92
17  6.11221E+11  SOWENDARYA P K  87  97.0    92
16  6.11221E+11   SOWANTHARYA S  87  96.0    92
15  6.11221E+11     SOURISH A P  87  95.0    92
..          ...             ...  ..   ...   ...
2   6.11221E+11     SARAVANAN S  85  90.0    95
35  6.11221E+11        SWETHA M  85  90.0    95
36  6.11221E+11    SYED ANEES J  85  90.0    95
34  6.11221E+11      SWETHA S M  85  90.0    95
0   6.11221E+11       SANTOSH M  85   NaN    78

[67 rows x 5 columns]

In [ ]:
df.sort_values(['Student’s Name','FDS'])

        Reg No.   Student’s Name  DS   FDS  OOPS
66          LE5  ABILASH KUMAR R  90  92.0    94
0   6.11221E+11        SANTOSH M  85   NaN    78
1   6.11221E+11        SARANYA A  85  90.0    95
2   6.11221E+11      SARAVANAN S  85  90.0    95
3   6.11221E+11  SARGURURATHNA M  85  90.0    95
..          ...              ...  ..   ...   ...
65          LE4        VIYASAN.S  85  90.0    95
58  6.11221E+11         YAMINI M  85  90.0    95
59  6.11221E+11        YUVARAJ R  85  90.0    95
60  6.11221E+11       YUVASREE M  85  90.0    95
61  6.11221E+11        YUVASRI V  85  90.0    95

[67 rows x 5 columns]

In [ ]:
# 0 represents descending order and 1 represents ascending order
df.sort_values(['Student’s Name','FDS'],ascending=[0,1])

        Reg No.   Student’s Name  DS  FDS  OOPS
61  6.11221E+11        YUVASRI V  85   90    95
60  6.11221E+11       YUVASREE M  85   90    95
59  6.11221E+11        YUVARAJ R  85   90    95
58  6.11221E+11         YAMINI M  85   90    95
65          LE4        VIYASAN.S  85   90    95
..          ...              ...  ..  ...   ...
4   6.11221E+11      SATHAPPAN V  85   90    95
3   6.11221E+11  SARGURURATHNA M  85   90    95
2   6.11221E+11      SARAVANAN S  85   90    95
1   6.11221E+11        SARANYA A  85   90    95
0   6.11221E+11        SANTOSH M  85   90    95

[66 rows x 5 columns]

# Add columns in a dataframe

In [ ]:
df['Total Marks'] = 0
df

        Reg No.   Student’s Name  DS   FDS  OOPS  Total Marks
0   6.11221E+11        SANTOSH M  85   NaN    78            0
1   6.11221E+11        SARANYA A  85  90.0    95            0
2   6.11221E+11      SARAVANAN S  85  90.0    95            0
3   6.11221E+11  SARGURURATHNA M  85  90.0    95            0
4   6.11221E+11      SATHAPPAN V  85  90.0    95            0
..          ...              ...  ..   ...   ...          ...
62          LE1          VIJAY.T  85  90.0    95            0
63          LE2          VIPIN.R  85  90.0    95            0
64          LE3   VISHNU BALAN.O  85  90.0    95            0
65          LE4        VIYASAN.S  85  90.0    95            0
66          LE5  ABILASH KUMAR R  90  92.0    94            0

[67 rows x 6 columns]

In [ ]:
df['Total Marks'] = df['DS'] + df['FDS'] + df['OOPS']
df

        Reg No.   Student’s Name  DS   FDS  OOPS  Total Marks
0   6.11221E+11        SANTOSH M  85   NaN    78          NaN
1   6.11221E+11        SARANYA A  85  90.0    95        270.0
2   6.11221E+11      SARAVANAN S  85  90.0    95        270.0
3   6.11221E+11  SARGURURATHNA M  85  90.0    95        270.0
4   6.11221E+11      SATHAPPAN V  85  90.0    95        270.0
..          ...              ...  ..   ...   ...          ...
62          LE1          VIJAY.T  85  90.0    95        270.0
63          LE2          VIPIN.R  85  90.0    95        270.0
64          LE3   VISHNU BALAN.O  85  90.0    95        270.0
65          LE4        VIYASAN.S  85  90.0    95        270.0
66          LE5  ABILASH KUMAR R  90  92.0    94        276.0

[67 rows x 6 columns]

In [ ]:
df

        Reg No.   Student’s Name  DS   FDS  OOPS  Total Marks
0   6.11221E+11        SANTOSH M  85   NaN    78          NaN
1   6.11221E+11        SARANYA A  85  90.0    95        270.0
2   6.11221E+11      SARAVANAN S  85  90.0    95        270.0
3   6.11221E+11  SARGURURATHNA M  85  90.0    95        270.0
4   6.11221E+11      SATHAPPAN V  85  90.0    95        270.0
..          ...              ...  ..   ...   ...          ...
62          LE1          VIJAY.T  85  90.0    95        270.0
63          LE2          VIPIN.R  85  90.0    95        270.0
64          LE3   VISHNU BALAN.O  85  90.0    95        270.0
65          LE4        VIYASAN.S  85  90.0    95        270.0
66          LE5  ABILASH KUMAR R  90  92.0    94        276.0

[67 rows x 6 columns]

#Drop Columns

In [ ]:
df.drop(columns = 'Total Marks')
#df
#df = df.drop(columns = 'Total Marks')

        Reg No.   Student’s Name  DS   FDS  OOPS
0   6.11221E+11        SANTOSH M  85   NaN    78
1   6.11221E+11        SARANYA A  85  90.0    95
2   6.11221E+11      SARAVANAN S  85  90.0    95
3   6.11221E+11  SARGURURATHNA M  85  90.0    95
4   6.11221E+11      SATHAPPAN V  85  90.0    95
..          ...              ...  ..   ...   ...
62          LE1          VIJAY.T  85  90.0    95
63          LE2          VIPIN.R  85  90.0    95
64          LE3   VISHNU BALAN.O  85  90.0    95
65          LE4        VIYASAN.S  85  90.0    95
66          LE5  ABILASH KUMAR R  90  92.0    94

[67 rows x 5 columns]

In [ ]:
df

        Reg No.   Student’s Name  DS   FDS  OOPS  Total Marks
0   6.11221E+11        SANTOSH M  85   NaN    78          NaN
1   6.11221E+11        SARANYA A  85  90.0    95        270.0
2   6.11221E+11      SARAVANAN S  85  90.0    95        270.0
3   6.11221E+11  SARGURURATHNA M  85  90.0    95        270.0
4   6.11221E+11      SATHAPPAN V  85  90.0    95        270.0
..          ...              ...  ..   ...   ...          ...
62          LE1          VIJAY.T  85  90.0    95        270.0
63          LE2          VIPIN.R  85  90.0    95        270.0
64          LE3   VISHNU BALAN.O  85  90.0    95        270.0
65          LE4        VIYASAN.S  85  90.0    95        270.0
66          LE5  ABILASH KUMAR R  90  92.0    94        276.0

[67 rows x 6 columns]

# EXPORT DATAFRAME TO EXCEL, CSV & TEXT FILE IN PANDAS -- SAVE DATAFRAME IN PANDAS

In [ ]:
#df.to_excel('new_marklist.xlsx')
#df.to_excel('new_marklist.xlsx',index= False)
#df.to_csv('new_marklist.csv')
#df.to_csv('new_marklist.csv',index= False)
df.to_csv('new_marklist.txt')
#df.to_csv('new_marklist.txt',index= False,sep='\t')

In [ ]:
df[['Reg No.', 'Total Marks']]

NameError: name 'df' is not defined

# Dataframe.loc[ ] :
* This function is used for displaying data in rows based on labels
#Syntax
Dataframe.loc[rows,cols(label)]
# Dataframe.iloc[ ] :
* This function is used for displaying data in rows based on positions or integer
#Syntax
Dataframe.iloc[rows,cols(index)]
# Dataframe.ix[] : This function is used for displaying data in rows based on both label and integer
Dataframe.ix[rows,cols(index or label)]

In [ ]:
df.loc[2]

Reg No.           6.11221E+11
Student’s Name    SARAVANAN S
DS                         85
FDS                      90.0
OOPS                       95
Name: 2, dtype: object

In [ ]:
df.loc[2,'Student’s Name']

'SARAVANAN S'

In [ ]:
df.loc[0:4,'Student’s Name']

0          SANTOSH M
1          SARANYA A
2        SARAVANAN S
3    SARGURURATHNA M
4        SATHAPPAN V
Name: Student’s Name, dtype: object

In [ ]:
df.loc[0:4,['Student’s Name','FDS']]

    Student’s Name  FDS
0        SANTOSH M   90
1        SARANYA A   90
2      SARAVANAN S   90
3  SARGURURATHNA M   90
4      SATHAPPAN V   90

In [ ]:
df.loc[0:4,'Student’s Name' :'OOPS']

    Student’s Name  DS   FDS  OOPS
0        SANTOSH M  85   NaN    78
1        SARANYA A  85  90.0    95
2      SARAVANAN S  85  90.0    95
3  SARGURURATHNA M  85  90.0    95
4      SATHAPPAN V  85  90.0    95

In [ ]:
# ilioc takes only index instead of columns
#df.iloc[0:4,'Student’s Name' :'Total Marks']
df.iloc[0:4,1 : 5]

    Student’s Name  DS   FDS  OOPS
0        SANTOSH M  85   NaN    78
1        SARANYA A  85  90.0    95
2      SARAVANAN S  85  90.0    95
3  SARGURURATHNA M  85  90.0    95

In [ ]:
df.iloc[0:4,0:5]

       Reg No.   Student’s Name  DS   FDS  OOPS
0  6.11221E+11        SANTOSH M  85   NaN    78
1  6.11221E+11        SARANYA A  85  90.0    95
2  6.11221E+11      SARAVANAN S  85  90.0    95
3  6.11221E+11  SARGURURATHNA M  85  90.0    95

In [ ]:
df.loc[0:5]

       Reg No.   Student’s Name  DS   FDS  OOPS
0  6.11221E+11        SANTOSH M  85   NaN    78
1  6.11221E+11        SARANYA A  85  90.0    95
2  6.11221E+11      SARAVANAN S  85  90.0    95
3  6.11221E+11  SARGURURATHNA M  85  90.0    95
4  6.11221E+11      SATHAPPAN V  85  90.0    95
5  6.11221E+11        SATHISH D  85  90.0    95

In [ ]:
df.iloc[0:5]

        Reg No.   Student’s Name  DS  FDS OOPS
0  611221104127        SANTOSH M  85   90
1  611221104128        SARANYA A  85   90   95
2  611221104129      SARAVANAN S  85   90   95
3  611221104130  SARGURURATHNA M  85   90   95
4  611221104131      SATHAPPAN V  85   90   95

In [ ]:
#df.iloc[[0,66]]
df.iloc[:,[0,4]]

        Reg No.  OOPS
0   6.11221E+11    78
1   6.11221E+11    95
2   6.11221E+11    95
3   6.11221E+11    95
4   6.11221E+11    95
..          ...   ...
62          LE1    95
63          LE2    95
64          LE3    95
65          LE4    95
66          LE5    94

[67 rows x 2 columns]

#Handling missing data

#(i)Remove mssing data
- dropna()

#(ii)Fill with default values
- fillna()

In [ ]:
#HANDLING MISSING DATA
rd = pd.read_excel("/content/sample_data/dropna_fillna.xlsx")
rd

         Reg No.   Student’s Name    DS   FDS  OOPS
0   611221104127        SANTOSH M  85.0  90.0   NaN
1   611221104128        SARANYA A  85.0  90.0  80.0
2   611221104129      SARAVANAN S   NaN  90.0   NaN
3   611221104129      SARAVANAN S   NaN  90.0   NaN
4   611221104130  SARGURURATHNA M  85.0  90.0   NaN
..           ...              ...   ...   ...   ...
64           LE1          VIJAY.T  85.0  90.0  95.0
65           LE2          VIPIN.R  85.0  90.0  95.0
66           LE3   VISHNU BALAN.O  85.0  90.0  95.0
67           LE4        VIYASAN.S  85.0  90.0  95.0
68           LE5  ABILASH KUMAR R  90.0  92.0  94.0

[69 rows x 5 columns]

#Rows with missing data

#0 2 3 4

In [ ]:
#its drops nan rows and cerate a new data frame
rd.dropna()

         Reg No.      Student’s Name    DS   FDS  OOPS
1   611221104128           SARANYA A  85.0  90.0  80.0
8   611221104134         SATHYARAM R  87.0  90.0  92.0
9   611221104135  SELVAGANAPATHI V M  87.0  90.0  92.0
10  611221104135  SELVAGANAPATHI V M  87.0  90.0  92.0
12  611221104137         SHABARI K S  87.0  90.0  92.0
..           ...                 ...   ...   ...   ...
64           LE1             VIJAY.T  85.0  90.0  95.0
65           LE2             VIPIN.R  85.0  90.0  95.0
66           LE3      VISHNU BALAN.O  85.0  90.0  95.0
67           LE4           VIYASAN.S  85.0  90.0  95.0
68           LE5     ABILASH KUMAR R  90.0  92.0  94.0

[61 rows x 5 columns]

In [ ]:
temp=rd.dropna()
temp

         Reg No.      Student’s Name    DS   FDS  OOPS
1   611221104128           SARANYA A  85.0  90.0  80.0
8   611221104134         SATHYARAM R  87.0  90.0  92.0
9   611221104135  SELVAGANAPATHI V M  87.0  90.0  92.0
10  611221104135  SELVAGANAPATHI V M  87.0  90.0  92.0
12  611221104137         SHABARI K S  87.0  90.0  92.0
..           ...                 ...   ...   ...   ...
64           LE1             VIJAY.T  85.0  90.0  95.0
65           LE2             VIPIN.R  85.0  90.0  95.0
66           LE3      VISHNU BALAN.O  85.0  90.0  95.0
67           LE4           VIYASAN.S  85.0  90.0  95.0
68           LE5     ABILASH KUMAR R  90.0  92.0  94.0

[61 rows x 5 columns]

In [ ]:
rd

         Reg No.   Student’s Name    DS   FDS  OOPS
0   611221104127        SANTOSH M  85.0  90.0   NaN
1   611221104128        SARANYA A  85.0  90.0  80.0
2   611221104129      SARAVANAN S   NaN  90.0   NaN
3   611221104129      SARAVANAN S   NaN  90.0   NaN
4   611221104130  SARGURURATHNA M  85.0  90.0   NaN
..           ...              ...   ...   ...   ...
64           LE1          VIJAY.T  85.0  90.0  95.0
65           LE2          VIPIN.R  85.0  90.0  95.0
66           LE3   VISHNU BALAN.O  85.0  90.0  95.0
67           LE4        VIYASAN.S  85.0  90.0  95.0
68           LE5  ABILASH KUMAR R  90.0  92.0  94.0

[69 rows x 5 columns]

In [ ]:
rd['OOPS'].dropna()

1     80.0
5     95.0
6     95.0
7     95.0
8     92.0
      ...
64    95.0
65    95.0
66    95.0
67    95.0
68    94.0
Name: OOPS, Length: 64, dtype: float64

In [ ]:
#HANDLING MISSING DATA
rd.loc[: ,['OOPS']].dropna()
#rd.loc[0:10 ,['OOPS']].dropna()

    OOPS
1   80.0
5   95.0
6   95.0
7   95.0
8   92.0
9   92.0
10  92.0

In [ ]:
rd

         Reg No.   Student’s Name    DS   FDS  OOPS
0   611221104127        SANTOSH M  85.0  90.0   NaN
1   611221104128        SARANYA A  85.0  90.0  80.0
2   611221104129      SARAVANAN S   NaN  90.0   NaN
3   611221104130  SARGURURATHNA M  85.0  90.0   NaN
4   611221104131      SATHAPPAN V  85.0   NaN  95.0
..           ...              ...   ...   ...   ...
63           LE1          VIJAY.T  85.0  90.0  95.0
64           LE2          VIPIN.R  85.0  90.0  95.0
65           LE3   VISHNU BALAN.O  85.0  90.0  95.0
66           LE4        VIYASAN.S  85.0  90.0  95.0
67           LE5  ABILASH KUMAR R  90.0  92.0  94.0

[68 rows x 5 columns]

In [ ]:
rd.fillna("MISSING")

         Reg No.   Student’s Name       DS   FDS     OOPS
0   611221104127        SANTOSH M     85.0  90.0  MISSING
1   611221104128        SARANYA A     85.0  90.0     80.0
2   611221104129      SARAVANAN S  MISSING  90.0  MISSING
3   611221104129      SARAVANAN S  MISSING  90.0  MISSING
4   611221104130  SARGURURATHNA M     85.0  90.0  MISSING
..           ...              ...      ...   ...      ...
64           LE1          VIJAY.T     85.0  90.0     95.0
65           LE2          VIPIN.R     85.0  90.0     95.0
66           LE3   VISHNU BALAN.O     85.0  90.0     95.0
67           LE4        VIYASAN.S     85.0  90.0     95.0
68           LE5  ABILASH KUMAR R     90.0  92.0     94.0

[69 rows x 5 columns]

In [ ]:
rd

         Reg No.   Student’s Name    DS   FDS  OOPS
0   611221104127        SANTOSH M  85.0  90.0   NaN
1   611221104128        SARANYA A  85.0  90.0  80.0
2   611221104129      SARAVANAN S   NaN  90.0   NaN
3   611221104130  SARGURURATHNA M  85.0  90.0   NaN
4   611221104131      SATHAPPAN V  85.0   NaN  95.0
..           ...              ...   ...   ...   ...
63           LE1          VIJAY.T  85.0  90.0  95.0
64           LE2          VIPIN.R  85.0  90.0  95.0
65           LE3   VISHNU BALAN.O  85.0  90.0  95.0
66           LE4        VIYASAN.S  85.0  90.0  95.0
67           LE5  ABILASH KUMAR R  90.0  92.0  94.0

[68 rows x 5 columns]

In [ ]:
#HANDLING MISSING DATA
#rd
#rd.dropna(inplace = True)
#rd

         Reg No.   Student’s Name       DS      FDS     OOPS
0   611221104127        SANTOSH M     85.0     90.0  MISSING
1   611221104128        SARANYA A     85.0     90.0     80.0
2   611221104129      SARAVANAN S  MISSING     90.0  MISSING
3   611221104130  SARGURURATHNA M     85.0     90.0  MISSING
4   611221104131      SATHAPPAN V     85.0  MISSING     95.0
..           ...              ...      ...      ...      ...
63           LE1          VIJAY.T     85.0     90.0     95.0
64           LE2          VIPIN.R     85.0     90.0     95.0
65           LE3   VISHNU BALAN.O     85.0     90.0     95.0
66           LE4        VIYASAN.S     85.0     90.0     95.0
67           LE5  ABILASH KUMAR R     90.0     92.0     94.0

[68 rows x 5 columns]

In [ ]:
#d.fillna("MISSING")
#rd

In [ ]:
#d.fillna("MISSING",inplace = True)
#rd

In [ ]:
#rd.loc[:,['DS','FDS']].dropna()
#rd

In [ ]:
#rd.loc[:,['DS','FDS']].fillna(50)
#rd

In [ ]:
#rd.fillna(50,inplace = True)
#rd['OOPS'].fillna(rd['OOPS'].mean())

In [ ]:
#import math
#rd['OOPS'].fillna(math.floor(rd['OOPS'].mean()))
rd

In [ ]:
#displaying rows which matched the given Criteria
df.loc[df['OOPS']>90].drop(columns =['Student’s Name', 'DS','FDS','Total Marks'])
#df.loc[df['FDS']>90]

        Reg No.  OOPS
1   6.11221E+11    95
2   6.11221E+11    95
3   6.11221E+11    95
4   6.11221E+11    95
5   6.11221E+11    95
..          ...   ...
62          LE1    95
63          LE2    95
64          LE3    95
65          LE4    95
66          LE5    94

[66 rows x 2 columns]

# REMOVE DUPLICATES FROM DATAFRAME
**(i)duplicated()** --> checking the duplicate rows

**(ii)drop_duplicates()** ---> drop the duplicates

In [ ]:
rd.duplicated()

0     False
1     False
2     False
3      True
4     False
      ...
64    False
65    False
66    False
67    False
68    False
Length: 69, dtype: bool

In [ ]:
rd.drop_duplicates()
#rd

         Reg No.   Student’s Name    DS   FDS  OOPS
0   611221104127        SANTOSH M  85.0  90.0   NaN
1   611221104128        SARANYA A  85.0  90.0  80.0
2   611221104129      SARAVANAN S   NaN  90.0   NaN
4   611221104130  SARGURURATHNA M  85.0  90.0   NaN
5   611221104131      SATHAPPAN V  85.0   NaN  95.0
..           ...              ...   ...   ...   ...
64           LE1          VIJAY.T  85.0  90.0  95.0
65           LE2          VIPIN.R  85.0  90.0  95.0
66           LE3   VISHNU BALAN.O  85.0  90.0  95.0
67           LE4        VIYASAN.S  85.0  90.0  95.0
68           LE5  ABILASH KUMAR R  90.0  92.0  94.0

[67 rows x 5 columns]

In [ ]:
#rd.loc[5:15].duplicated()

In [ ]:
#rd.drop_duplicates(inplace = True)

In [ ]:
#rd.loc[5:10]

In [ ]:
#rd.loc[:20]

In [ ]:
rd

         Reg No.   Student’s Name    DS   FDS  OOPS
0   611221104127        SANTOSH M  85.0  90.0   NaN
1   611221104128        SARANYA A  85.0  90.0  80.0
2   611221104129      SARAVANAN S   NaN  90.0   NaN
3   611221104129      SARAVANAN S   NaN  90.0   NaN
4   611221104130  SARGURURATHNA M  85.0  90.0   NaN
..           ...              ...   ...   ...   ...
64           LE1          VIJAY.T  85.0  90.0  95.0
65           LE2          VIPIN.R  85.0  90.0  95.0
66           LE3   VISHNU BALAN.O  85.0  90.0  95.0
67           LE4        VIYASAN.S  85.0  90.0  95.0
68           LE5  ABILASH KUMAR R  90.0  92.0  94.0

[69 rows x 5 columns]

# DATA FILTERING

In [ ]:
#rd.loc[rd['FDS']>90]

         Reg No.       Student’s Name    DS   FDS  OOPS
9   611221104135   SELVAGANAPATHI V M  87.0  90.0  92.0
10  611221104135   SELVAGANAPATHI V M  87.0  90.0  92.0
11  611221104136       SETHURAMAN C R  87.0  90.0   NaN
12  611221104137          SHABARI K S  87.0  90.0  92.0
13  611221104138           SHARMILA S  87.0  91.0  92.0
14  611221104139           SHIBIE R M  87.0  92.0  92.0
15  611221104140       SHREENIVASAN S  87.0  93.0  92.0
16  611221104141          SHRIYAA S V  87.0  94.0  92.0
17  611221104142          SOURISH A P  87.0  95.0  92.0
18  611221104143        SOWANTHARYA S  87.0  96.0  92.0
19  611221104144       SOWENDARYA P K  87.0  97.0  92.0
20  611221104145          SOWNDARYA K  87.0  98.0  92.0
21  611221104146          SREEJITHA S  85.0  99.0  95.0
22  611221104147   SREE SUDHARSAN A M  85.0  90.0  95.0
23  611221104148  SRIPOORNIMADEVI T S  85.0  90.0  95.0
24  611221104149         SRIRANJANI M  85.0  90.0  95.0
25  611221104151             SUBASH S  85.0  90.0  95.0
26  611221104152            SUBASRI C  85.0  90.0  95.0
27  611221104153           SUBESHAN M  85.0  90.0  95.0
28  611221104154         SUBIKCHA K B  85.0  90.0  95.0
29  611221104155       SUDHARSHAN M S  85.0  90.0  95.0
30  611221104156      SUGANESHWARAN S  85.0  90.0  95.0
31  611221104157    SUGAVANESHWARAN K  85.0  90.0  95.0
32  611221104158           SUHASINI P  85.0  90.0  95.0
33  611221104159          SUNDARESH S  85.0  90.0  95.0
34  611221104160        SUSHMITHA B A  85.0  90.0  95.0
35  611221104161             SWATHI V  85.0  90.0  95.0
36  611221104163           SWETHA S M  85.0  90.0  95.0
37  611221104162             SWETHA M  85.0  90.0  95.0
38  611221104164         SYED ANEES J  85.0  90.0  95.0
39  611221104166            THARANI R  85.0  90.0  95.0
40  611221104165            THARANI K  85.0  90.0  95.0
41  611221104167      THOUSHIKAMARY F  85.0  90.0  95.0
42  611221104168             THREKA M  85.0  90.0  95.0
43  611221104169           TRISHA J V  85.0  90.0  95.0
44  611221104170        UDHAYAKIRAN G  85.0  90.0  95.0
45  611221104171           VAISHIYA R  85.0  90.0  95.0
46  611221104172         VALLIAPPAN V  85.0  90.0  95.0
47  611221104173           VARSHINI G  85.0  90.0  95.0
48  611221104174         VENKATESAN M  85.0  90.0  95.0
49  611221104175          VENKATESH K  85.0  90.0  95.0
50  611221104176          VENKATRAM S  85.0  90.0  95.0
51  611221104177              VIBAV M  85.0  90.0  95.0
52  611221104178            VIGNESH S  85.0  90.0  95.0
53  611221104179       VIGNESHWARAN K  85.0  90.0  95.0
54  611221104180            VIJAY K R  85.0  90.0  95.0
55  611221104181        VIJAYAKUMAR G  85.0  90.0  95.0
56  611221104182              VIKAS P  85.0  90.0  95.0
57  611221104183          VINEETH K R  85.0  90.0  95.0
58  611221104184           VISHNAVI R  85.0  90.0  95.0
59  611221104185              VIVEK S  85.0  90.0  95.0
60  611221104186             YAMINI M  85.0  90.0  95.0
61  611221104187            YUVARAJ R  85.0  90.0  95.0
62  611221104188           YUVASREE M  85.0  90.0  95.0
63  611221104189            YUVASRI V  85.0  90.0  95.0
64           LE1              VIJAY.T  85.0  90.0  95.0
65           LE2              VIPIN.R  85.0  90.0  95.0
66           LE3       VISHNU BALAN.O  85.0  90.0  95.0
67           LE4            VIYASAN.S  85.0  90.0  95.0
68           LE5      ABILASH KUMAR R  90.0  92.0  94.0

In [ ]:
#rd.loc[(rd['FDS']> 90) & (rd['OOPS']>90)]

In [ ]:
#rd.loc[(rd['FDS']> 90) | (rd['FDS']>90)]

In [ ]:
#rd.loc[(rd['DS'] > 85) & (rd['FDS']>90) & (rd['FDS']>90)]

In [ ]:
#rd.loc[rd['Student’s Name'].str.contains("SA")]

In [ ]:
#rd.loc[~rd['Student’s Name'].str.contains("SA")]

In [ ]:
#rd.loc[rd['Student’s Name'].str.startswith("SA")]

In [ ]:
rd.loc[~rd['Student’s Name'].str.startswith("SA")]

In [ ]:
#rd.loc[rd['Student’s Name'].str.endswith("SA")]

In [ ]:
#rd.loc[~rd['Student’s Name'].str.endswith("SA")]

In [ ]:
#rd

# CONDITIONAL CHANGES IN PYTHON

In [ ]:
'''
O   -->  91 - 100
A+  -->  81 - 90
A   -->  71 - 80
B+  -->  61 - 70
B   -->  50 - 60
U   -->  <50
PERCENTAGE >= 85  --->  DISTINCTION
PERCENTAGE >= 70  --->  FIRST CLASS
PERCENTAGE < 70   --->   SECOND CLASS
PERCENTAGE < 50   --->   FAIL'''


rd['Total'] = rd['DS'] + rd['FDS'] + rd['OOPS']
rd['Percentage'] = (rd['Total']/300)*100
rd

         Reg No.   Student’s Name    DS   FDS  OOPS  Total  Percentage
0   611221104127        SANTOSH M  85.0  90.0   NaN    NaN         NaN
1   611221104128        SARANYA A  85.0  90.0  80.0  255.0        85.0
2   611221104129      SARAVANAN S   NaN  90.0   NaN    NaN         NaN
3   611221104129      SARAVANAN S   NaN  90.0   NaN    NaN         NaN
4   611221104130  SARGURURATHNA M  85.0  90.0   NaN    NaN         NaN
..           ...              ...   ...   ...   ...    ...         ...
64           LE1          VIJAY.T  85.0  90.0  95.0  270.0        90.0
65           LE2          VIPIN.R  85.0  90.0  95.0  270.0        90.0
66           LE3   VISHNU BALAN.O  85.0  90.0  95.0  270.0        90.0
67           LE4        VIYASAN.S  85.0  90.0  95.0  270.0        90.0
68           LE5  ABILASH KUMAR R  90.0  92.0  94.0  276.0        92.0

[69 rows x 7 columns]

In [ ]:
#rd['Percentage'] = rd['Total'] / 3
#rd['Grade'] = 'None'

In [ ]:
rd.loc[(rd['Percentage'] >= 85) , ['Grade']] = "DISTINCTION"
rd

,Reg No.,Student’s Name,DS,FDS,OOPS,Total,Percentage,Grade
0,611221104127,SANTOSH M,85.0,90.0,NaN,NaN,NaN,NaN
1,611221104128,SARANYA A,85.0,90.0,80.0,255.0,85.0,DISTINCTION
2,611221104129,SARAVANAN S,NaN,90.0,NaN,NaN,NaN,NaN
3,611221104129,SARAVANAN S,NaN,90.0,NaN,NaN,NaN,NaN
4,611221104130,SARGURURATHNA M,85.0,90.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
64,LE1,VIJAY.T,85.0,90.0,95.0,270.0,90.0,DISTINCTION
65,LE2,VIPIN.R,85.0,90.0,95.0,270.0,90.0,DISTINCTION
66,LE3,VISHNU BALAN.O,85.0,90.0,95.0,270.0,90.0,DISTINCTION
67,LE4,VIYASAN.S,85.0,90.0,95.0,270.0,90.0,DISTINCTION
68,LE5,ABILASH KUMAR R,90.0,92.0,94.0,276.0,92.0,DISTINCTION

In [ ]:
rd.loc[((rd['Percentage'] >= 70) & (rd['Percentage'] < 85) ) , ['Grade']] = "FIRST CLASS"
rd

,Reg No.,Student’s Name,DS,FDS,OOPS,Total,Percentage,Grade
0,611221104127,SANTOSH M,85.0,90.0,NaN,NaN,NaN,NaN
1,611221104128,SARANYA A,85.0,90.0,80.0,255.0,85.0,DISTINCTION
2,611221104129,SARAVANAN S,NaN,90.0,NaN,NaN,NaN,NaN
3,611221104129,SARAVANAN S,NaN,90.0,NaN,NaN,NaN,NaN
4,611221104130,SARGURURATHNA M,85.0,90.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
64,LE1,VIJAY.T,85.0,90.0,95.0,270.0,90.0,DISTINCTION
65,LE2,VIPIN.R,85.0,90.0,95.0,270.0,90.0,DISTINCTION
66,LE3,VISHNU BALAN.O,85.0,90.0,95.0,270.0,90.0,DISTINCTION
67,LE4,VIYASAN.S,85.0,90.0,95.0,270.0,90.0,DISTINCTION
68,LE5,ABILASH KUMAR R,90.0,92.0,94.0,276.0,92.0,DISTINCTION

In [ ]:
rd.loc[((rd['Percentage'] >= 50) & (rd['Percentage'] < 70) ) , ['Grade']] = "SECOND CLASS"
rd

,Reg No.,Student’s Name,DS,FDS,OOPS,Total,Percentage,Grade
0,611221104127,SANTOSH M,85.0,90.0,NaN,NaN,NaN,NaN
1,611221104128,SARANYA A,85.0,90.0,80.0,255.0,85.0,DISTINCTION
2,611221104129,SARAVANAN S,NaN,90.0,NaN,NaN,NaN,NaN
3,611221104129,SARAVANAN S,NaN,90.0,NaN,NaN,NaN,NaN
4,611221104130,SARGURURATHNA M,85.0,90.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
64,LE1,VIJAY.T,85.0,90.0,95.0,270.0,90.0,DISTINCTION
65,LE2,VIPIN.R,85.0,90.0,95.0,270.0,90.0,DISTINCTION
66,LE3,VISHNU BALAN.O,85.0,90.0,95.0,270.0,90.0,DISTINCTION
67,LE4,VIYASAN.S,85.0,90.0,95.0,270.0,90.0,DISTINCTION
68,LE5,ABILASH KUMAR R,90.0,92.0,94.0,276.0,92.0,DISTINCTION

In [ ]:
rd.loc[rd['Percentage'] < 50 , ['Grade']] = "FAIL"
rd

,Reg No.,Student’s Name,DS,FDS,OOPS,Total,Percentage,Grade
0,611221104127,SANTOSH M,85.0,90.0,NaN,NaN,NaN,NaN
1,611221104128,SARANYA A,85.0,90.0,80.0,255.0,85.0,DISTINCTION
2,611221104129,SARAVANAN S,NaN,90.0,NaN,NaN,NaN,NaN
3,611221104129,SARAVANAN S,NaN,90.0,NaN,NaN,NaN,NaN
4,611221104130,SARGURURATHNA M,85.0,90.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
64,LE1,VIJAY.T,85.0,90.0,95.0,270.0,90.0,DISTINCTION
65,LE2,VIPIN.R,85.0,90.0,95.0,270.0,90.0,DISTINCTION
66,LE3,VISHNU BALAN.O,85.0,90.0,95.0,270.0,90.0,DISTINCTION
67,LE4,VIYASAN.S,85.0,90.0,95.0,270.0,90.0,DISTINCTION
68,LE5,ABILASH KUMAR R,90.0,92.0,94.0,276.0,92.0,DISTINCTION

#Group by
* The groupby() method in pandas is used to group data by one or more columns.

#First
* The first() method is often used after groupby() to return the first value in each group.
* This can be particularly useful for getting a representative value from each group.

In [ ]:
# importing pandas as pd for using data frame
import pandas as pd

# creating dataframe with student details
dataframe = pd.DataFrame({'id': [7058, 4511, 7014, 7033],
						'name': ['sravan', 'manoj', 'aditya', 'bhanu'],
						'Maths_marks': [99, 97, 88, 90],
						'Chemistry_marks': [89, 99, 99, 90],
						'telugu_marks': [99, 97, 88, 80],
						'hindi_marks': [99, 97, 56, 67],
						'social_marks': [79, 97, 78, 90], })

# group by name
print(dataframe.groupby('name').first())

          id  Maths_marks  Chemistry_marks  telugu_marks  hindi_marks  \
name
aditya  7014           88               99            88           56
bhanu   7033           90               90            80           67
manoj   4511           97               99            97           97
sravan  7058           99               89            99           99

        social_marks
name
aditya            78
bhanu             90
manoj             97
sravan            79
------------------------
name
aditya    78
bhanu     90
manoj     97
sravan    79
Name: social_marks, dtype: int64
------------------------
name
aditya    1
bhanu     1
manoj     1
sravan    1
Name: Maths_marks, dtype: int64

In [ ]:
print("------------------------")
# group by name with social_marks sum
print(dataframe.groupby('name')['social_marks'].sum())

In [ ]:
print("------------------------")
# group by name with maths_marks count
print(dataframe.groupby('name')['Maths_marks'].count())